### ISSUE TITLE
Use along with pybind11

### ISSUE THREAD

**Issue by Rhvarrier** [pocketpy/pocketpy#117]
Can this library be used along with pybind11, i.e. pybind11 currently needs to link with CPython, can pocketpy be used instead. This would allow to have a completely standalone (zero dependency python binding and interpreter)

**Comment by blueloveTH** [comment]
You need to use `vm->bind()` and other builtin binding apis. pocketpy does not support 3rd binding generator.

**Comment by Rhvarrier** [comment]
Is pybind11 support planned in the future?

**Comment by blueloveTH** [comment]
That isn't possible. pocketpy uses protocols different from cpython.

**Comment by Rhvarrier** [comment]
@blueloveTH I see that this issue has been reopened, is there any plans to make it work with pybind11 as it would be awesome

**Comment by blueloveTH** [comment]
Yes. I want to apply GSoC program. If successful, I could find a contributor to develop a pybind11-compatible binding solution. So I reopened this issue.

**Comment by blueloveTH** [comment]
pybind11 is available in main branch now.

**Comment by 16bit-ykiko** [comment]
pybind11 is now part of the pocketpy, located in `include/pybind11`. You can use it directly by including it, without needing to do anything else. The README has been updated, and documentation updates are in progress.

**Comment by 16bit-ykiko** [comment]
In fact, it's not pocketpy that adapts to pybind11, but rather I have rewritten pybind11 specifically for pocketpy, providing compatibility interfaces.

**Comment by Rhvarrier** [comment]
> In fact, it's not pocketpy that adapts to pybind11, but rather I have rewritten pybind11 specifically for pocketpy, providing compatibility interfaces.

Ok that's an interesting approach. Have you planned to integrate these changes into pybind11 as well so that it will easier to maintain upstream?

**Comment by blueloveTH** [comment]
@Rhvarrier Docs available here! https://pocketpy.dev/pybind11/

**Comment by 16bit-ykiko** [comment]
>Ok that's an interesting approach. Have you planned to integrate these changes into pybind11 as well so that it will easier to maintain upstream?

No, although it provides compatibility interfaces, the internal implementation is very different. For example, pybind11 is mainly written in C++11, but pocketpy is written in C++17. This allows me to use some C++17 features to make the compilation faster and the code more readable, such as using `if constexpr` to replace template specialization and using fold expressions to expand variadic templates.
