### ISSUE TITLE
Non literal parameters on functions needed

### ISSUE THREAD

**Issue by miratcan** [pocketpy/pocketpy#171]
I'am using PocketPY with TIC-80, when I try to run this:

![Screenshot 2023-10-23 at 13 17 55](https://github.com/blueloveTH/pocketpy/assets/140968/8a368017-d079-4c2c-9348-d00e7a732cac)

Python interpreter complains about the parameter type:

![Screenshot 2023-10-23 at 13 16 49](https://github.com/blueloveTH/pocketpy/assets/140968/78ca3be8-7beb-457f-b1b5-660f85f6525c)

These are very basic and required type of parameterization I think.

**Comment by blueloveTH** [comment]
You can achieve the same result by this.

```python
class Box:
  def __init__(self, size_method=None):
    size_method = size_method or (HUG, HUG)
```

**Comment by blueloveTH** [comment]
It is unsafe to use non-literals as default argmuents. Though cpython allows this, I don't think this is a good style.

I have no plan to support it.
