### ISSUE TITLE
[Question] Is it possible to load/save compiled bytecode ?

### ISSUE THREAD

**Issue by qtnc** [pocketpy/pocketpy#185]
Hello,

The question is quite simple, sorry if it has already been answered. Is it possible to:

1. Compile some python code
2. Save compiled bytecode to disk
3. Reload previously saved bytecode later
4. Run it

IF yes:

* Does each import have to be compiled and reloaded separately, or can a whole big script be compiled and reloaded at once ?
* Does the whole set of registered classes/methods/functions have to be exactly the same between the time the code is compiled and the time it is run ?
* CAn python code be compiled without the need to register the complete set of classes/methods/functions that will be used at run time ?
* Can bytecode compiled with an older version of PocketPy be reloaded in a newer version ?

Thank you for your answers. IF this feature isn't implemented yet, take it as a feature proposal. It would be good to have it, so that end users wouldn't necessarily see the code created by scripters/makers in clear.

**Comment by blueloveTH** [comment]
NO.

**Comment by blueloveTH** [comment]
I know you want to encrypt the code. This is possible but not necessary to be implemented as bytecode serialization. Because it is must more complex.

**Comment by blueloveTH** [comment]
This feature was added: https://pocketpy.dev/features/precompile/#string-precompilation
