### ISSUE TITLE
[Feature] Replace fmt with fmt_ v or something else

### ISSUE THREAD

**Issue by AstroAir** [pocketpy/pocketpy#194]
When I was programming, my project included both `fmt` and `pocketpy`. However, when I tried to compile, I encountered an error with `the reference to 'fmt' being ambiguous`. I will replace the `fmt` function with `fmt_ v`, the error disappeared. I don't know if it was the problem I set up, but the modifications were indeed useful.

```
pocketpy.h(1677, 24): In instantiation of 'struct pkpy::SmallNameDict<pkpy::PyObject*>':
pocketpy.h(1906, 27): required from 'union pkpy::NameDictImpl<pkpy::PyObject*>::<unnamed>'
pocketpy.h(1905, 6): required from 'struct pkpy::NameDictImpl<pkpy::PyObject*>'
pocketpy.h(1990, 31): required from here
type_traits(3230, 25): declared here
'std::is_pod_v<int>' is deprecated: use 'is_standard_layout_v && is_trivial_v' instead [-Wdeprecated-declarations]GCC
```
std::is_standard_layout_v<V> && std::is_trivial_v<V>

Another question is _ conflict with the abbreviation of regular gettext, I'm not sure if there's any way to resolve it.

**Comment by blueloveTH** [comment]
What is the version being used? Are you using the main branch, single header version or cmake?

**Comment by blueloveTH** [comment]
You will use something like `std::fmt`, not just `fmt`. Because our fmt is `pkpy::fmt`. They are in different namespaces so they won't be conflict with each other.

**Comment by blueloveTH** [comment]
About std::is_standard_layout_v && std::is_trivial_v, please provide more details I don't understand what you mentioned about.

**Comment by AstroAir** [comment]
Sorry, my expression is too vague,I am using a single header file version of 1.4.0(It should be the latest release).

Regarding fmt, I think there may be a conflict with the fmt library. I did not use using namespace pkpy or using namespace fmt, but conflicts still occur.

line 1674
```cpp
template<typename V>
struct SmallNameDict{
    using K = StrName;
    static_assert(std::is_pod_v<T>);
```
This cause a warning, so I changed it
```cpp
template<typename V>
struct SmallNameDict{
    using K = StrName;
    static_assert(std::is_standard_layout_v<V> && std::is_trivial_v<V>);
```
but I find in line 367, there is already a solution
```cpp
template<typename T>
struct is_pod {
	static constexpr bool value = std::is_trivially_copyable_v<T> && std::is_standard_layout_v<T>;
};
```

**Comment by blueloveTH** [comment]
`fmt` in pkpy is an internal api. I will rename and hide it.

For the 2nd problem, I think this is a bug. It should be `pkpy::is_pod`.

**Comment by AstroAir** [comment]
Thank you very much, waiting for your repair.
