### ISSUE TITLE
only see add_module_cjson declaration in pocketpy.h

### ISSUE THREAD

**Issue by miyanyan** [pocketpy/pocketpy#198]
hi, I found there's an option `PK_USE_CJSON`, and when I search it in pocketpt.h, there's a function: 
```
#ifdef PK_USE_CJSON
void add_module_cjson(VM* vm);
#endif
```
but I can't find the implementation, is cjson not supported in single header pocketpy.h?
![image](https://github.com/pocketpy/pocketpy/assets/40262194/0b8430df-c5f6-48b8-a821-38b1d0ec69e6)

**Comment by blueloveTH** [comment]
Single header version does support 3rd extensions.

If you need cJSON, you can use CMake to config it. Or use pkpy's built in JSON.

**Comment by miyanyan** [comment]
thanks
