### ISSUE TITLE
Any way to force the interpreter to stop?

### ISSUE THREAD

**Issue by stautonico** [pocketpy/pocketpy#200]
I am writing a program that allows users to enter their own python code, however I need some security around that. I have been able to sandbox the vm as much as possible, however I see no way to stop something like an infinite loop from happening without terminating the entire program. Is there any way to signal the interpreter to stop? I tried multi-threading, but I can't seem to find a way to force a thread to stop. 

Does pocketpy have any way to force kill the interpreter?

**Comment by stautonico** [comment]
Ah I see the general idea here, but I'm having a hard time getting it to compile. I set the `#define PK_ENABLE_CEVAL_CALLBACK    1` in my user_config, but I'm getting a "error: ‘class MyVM’ has no member named ‘_ceval_on_step’" after copying the example almost line for line.  I'm also getting "Error: no matching function for call to ‘MyVM::_error(const char [18], const char [1])’"

Here is my custom vm class:

```cpp
#include <atomic>
#include <iostream>
#include <signal.h>
#include <thread>

#define PK_USER_CONFIG_H
#include <pocketpy.h>
using namespace pkpy;
class MyVM : public VM {
public:
    // use atomic to protect the flag
    std::atomic<bool> _flag = false;

    MyVM() : VM() {
        this->_ceval_on_step = [](VM *_vm, Frame *frame, Bytecode bc) {
            MyVM *vm = (MyVM *) _vm;
            if (vm->_flag) {
                vm->_flag = false;
                vm->KeyboardInterrupt();
            }
        };
    }
    void KeyboardInterrupt() {
        _error("KeyboardInterrupt", "");
    }
};
```

I tried a clean build and pulling the latest version of pocketpy, but it still doesn't work.

**Comment by blueloveTH** [comment]
It just demonstrates the idea. The actual api could change. You can go back to an old version or take a look at vm.h to learn internal apis.



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 14, 2024 08:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pocketpy/pocketpy] Any way to force the interpreter to stop?(Issue #200)




 
Ah I see the general idea here, but I'm having a hard time getting it to compile. I set the #define PK_ENABLE_CEVAL_CALLBACK    1 in my user_config, but I'm getting a "error: ‘class MyVM’ has no member named ‘_ceval_on_step’" after copying the example almost line for line.  I'm also getting "Error: no matching function for call to ‘MyVM::_error(const char [18], const char [1])’"
 
Here is my custom vm class:
 #include <atomic&gt; #include <iostream&gt; #include <signal.h&gt; #include <thread&gt; #define PK_USER_CONFIG_H #include <pocketpy.h&gt; using namespace pkpy; class MyVM : public VM { public:     // use atomic to protect the flag     std::atomic<bool&gt; _flag = false;     MyVM() : VM() {         this-&gt;_ceval_on_step = [](VM *_vm, Frame *frame, Bytecode bc) {             MyVM *vm = (MyVM *) _vm;             if (vm-&gt;_flag) {                 vm-&gt;_flag = false;                 vm-&gt;KeyboardInterrupt();             }         };     }     void KeyboardInterrupt() {         _error("KeyboardInterrupt", "");     } };
 
I tried a clean build and pulling the latest version of pocketpy, but it still doesn't work.
