### ISSUE TITLE
[BUG] Can't import modules in unity plugin

### ISSUE THREAD

**Issue by IRISHMAN04** [pocketpy/pocketpy#201]
### Bug description
Import statements in unity plugin throw errors
Happens with any import statement, os is used here because it is listed https://pocketpy.dev/modules/os/ as an implemented module
![image](https://github.com/pocketpy/pocketpy/assets/40749529/6db73c49-ccd2-49ff-a49c-fb529d334d95)

### Steps to reproduce
- Import all from package manager
- Add this code to a class
[MenuItem("Python/Test2")]
    static void Test2()
    {
        Debug.Log("Starting");
        var vm = new VM();
        const string source = "import os";
        CodeObject code = vm.Compile(source, "main.py", CompileMode.EXEC_MODE);
        vm.Exec(code);
        Debug.Log("Finished");
    }
- Click Python/Test2 from top menu bar
Do all the above, or
- Follow steps in the following image after importing all from package manager
![image](https://github.com/pocketpy/pocketpy/assets/40749529/85ac888d-226b-4d4a-991a-7828e6560ad8)

### Environment information
- pocketpy's version: 1.1.4
- platform string: win32
- 64-bit
- unity version: 2022.3.8f1

**Comment by blueloveTH** [comment]
See `TestEditorVM.cs`.
```csharp
using UnityEngine;
using PocketPython;

[EditorVM]
public class TestEditorVM : VM
{
    public TestEditorVM()
    {
        RegisterAutoType<GameObject>(builtins);
        RegisterAutoType<Transform>(builtins);
        RegisterAutoType<Vector2>(builtins);
        RegisterAutoType<Vector3>(builtins);
    }
}
```

Currently, `RegisterAutoType` injects some class from UnityEngine into builtins. So you don't need to `import UnityEngine`, just directly use these classes without any import.

Also, pkpy is a sandbox by default. You can only access registered things.

`os` is not supported.

**Comment by blueloveTH** [comment]
C# impl of pkpy is completely a different thing with this repo.
Feel free to alter the C# source code & do customization.
