### ISSUE TITLE
[BUG] only export c api

### ISSUE THREAD

**Issue by miyanyan** [pocketpy/pocketpy#204]
### Bug description
if build as shared library, the code in readme will fail with link error on windows, because currently the cpp functions are not exported

### Steps to reproduce
- build as shared library
- link the dll
- run the example code
```cpp
#include "pocketpy.h"

using namespace pkpy;

int main(){
    // Create a virtual machine
    VM* vm = new VM();

    // Hello world!
    vm->exec("print('Hello world!')");

    // Create a list
    vm->exec("a = [1, 2, 3]");

    // Eval the sum of the list
    PyObject* result = vm->eval("sum(a)");
    std::cout << py_cast<int>(vm, result);   // 6

    // Bindings
    vm->bind(vm->_main, "add(a: int, b: int)",
      [](VM* vm, ArgsView args){
        int a = py_cast<int>(vm, args[0]);
        int b = py_cast<int>(vm, args[1]);
        return py_var(vm, a + b);
      });

    // Call the function
    PyObject* f_add = vm->_main->attr("add");
    result = vm->call(f_add, py_var(vm, 3), py_var(vm, 7));
    std::cout << py_cast<int>(vm, result);   // 10

    // Dispose the virtual machine
    delete vm;
    return 0;
}
```

### Environment information
You need to provide these strings:
- pocketpy's version
  main branch
- platform string (win32/linux/darwin/emscripten/android/ios)
  win32
- 32-bit or 64-bit
  64

### Additional context
* some projects will set a macro like https://github.com/gabime/spdlog/blob/v1.x/CMakeLists.txt#L161, so if it's ok I can make a pr like this.
* I find that pocketpy use `amalgamate.py` to generate `pocketpy.h` but not add the script to CMakeLists.txt, maybe can add a pocketpy::headeronly like https://github.com/gabime/spdlog/blob/v1.x/CMakeLists.txt#L199

* btw, I want to add pocketpy to vcpkg and vcpkg need `cmake install`, if it's ok I will also add the install scripts.

**Comment by blueloveTH** [comment]
Hi @miyanyan Currently it is not safe to export c++ api. Only c api is verified in dynamic linking mode.

Since pkpy is ultra lightweight, it is designed for static linking. I will not provide support for dynamic linking cpp parts.

**Comment by blueloveTH** [comment]
Header only mode is provided via Github Release. It is not necessary to add it into CMake.

**Comment by blueloveTH** [comment]
Nevertheless, you can upload to vcpkg and add your favorite install scripts. If you have time to upgrade it on new versions.

The biggest problem of most package managers is, packages could be outdated.

**Comment by miyanyan** [comment]
> Nevertheless, you can upload to vcpkg and add your favorite install scripts. If you have time to upgrade it on new versions.
> 
> The biggest problem of most package managers is, packages could be outdated.

thanks for reply, so I can use pocketpy with static linking or the single header.
I can update the version to vcpkg when new release comes.

cmake install can generate a xxx-config.cmake file and help the user to use library with `find_package(xxx CONFIG REQUIRED)`,  would you mind add some code to CMakeLists.txt like:
```
option(PK_INSTALL "Generate the install target" ON)
if (PK_INSTALL)
    install(
        TARGETS ${PROJECT_NAME}
        EXPORT ${PROJECT_NAME}_target
        ARCHIVE DESTINATION lib
        LIBRARY DESTINATION lib
        RUNTIME DESTINATION bin
    )

    install(
        DIRECTORY include/ 
        DESTINATION include 
        FILES_MATCHING PATTERN "*.h")

    install(
        EXPORT ${PROJECT_NAME}_target
        FILE ${PROJECT_NAME}-config.cmake
        DESTINATION "share/${PROJECT_NAME}"
    )
endif()
```

**Comment by blueloveTH** [comment]
Yes, you can submit a PR!

And please add a unit test file `run_cmake_install_test.sh` to ensure `cmake install` works.
