### ISSUE TITLE
[BUG] Incorrect representation of nanj in cmath module

### ISSUE THREAD

**Issue by faze-geek** [pocketpy/pocketpy#211]
Thanks for taking the time to fill out a bug report!
Please provide a descriptive title above and fill in the following fields.

### Bug description
You can paste sources here that may cause the error.
The `nanj` is a special number used in the `cmath` module and it has been implemented here -
https://github.com/pocketpy/pocketpy/blob/842c415a9f88249d67802eff2389765858332d9a/python/cmath.py#L169-L172

pocketpy main
```
>>> import cmath
>>> z_inf = cmath.infj
>>> z_inf
(0.0+infj)
>>> z_nanj = cmath.nanj
>>> z_nanj
(0.0nanj)             # This does not make sense without +
```

Python 3.9
```
>>> import cmath
>>> z_inf = cmath.infj
>>> z_inf
infj
>>> z_nanj = cmath.nanj
>>> z_nanj
nanj
```

**Comment by blueloveTH** [comment]
Feel free to submit a pr to fix it~

**Comment by blueloveTH** [comment]
Use the least-specialized solution. I think `(0.0+nanj)` is.

**Comment by blueloveTH** [comment]
I have time today and I'd like to fix it myself.

**Comment by faze-geek** [comment]
> I have time today and I'd like to fix it myself.

No issues @blueloveTH . It's late night here in India and I won't be fixing it anytime in the next 8 - 10 hours. Go ahead :)
