### ISSUE TITLE
Exponents with sign should be recognized as decimal numbers.

### ISSUE THREAD

**Issue by faze-geek** [pocketpy/pocketpy#213]
Python 3.9 - 
```
>>> a = 1e2
>>> a
100.0
>>> a = 1e-2
>>> a
0.01
```
Pocketpy - 
```
>>> a = 1e2
>>> a
100.0
>>> a = 1e-2
  File "<stdin>", line 1
    a = 1e-2
          ^
SyntaxError: invalid number literal
>>> a = 1e+2
  File "<stdin>", line 1
    a = 1e+2
          ^
SyntaxError: invalid number literal
```

**Comment by faze-geek** [comment]
This is not really an error in code but an extension of the partial implementation of exponentiation that is already supported in pocketpy. Hence, I didn't open it up as a bug.

**Comment by blueloveTH** [comment]
I know about this. But I am reluctant to fix it.

**Comment by carlkl** [comment]
Could this be noted in https://pocketpy.dev/features/differences/, as this kind of literals are quite common?

**Comment by faze-geek** [comment]
As mentioned in the documentation pocketpy is a project also being heavily used for scientific computing. In that context it is crucial to have special numbers/constants like (`Inf`, `eps`, `e`, `pi` etc.) and their various formats.
Hence I'm a bit confused on the reluctance to support this literal.
