### ISSUE TITLE
CPython does not admit leading 0 in ints without an o or [xX]

### ISSUE THREAD

**Issue by faze-geek** [pocketpy/pocketpy#222]
Python 
```
>>> (0000007 == 7)
  File "<stdin>", line 1
    (0000007 == 7)
     ^^^^^^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

Pocketpy
```
>>> (0000007 == 7)
True
```

**Comment by faze-geek** [comment]
Hi @blueloveTH, let me know if you would like this to be fixed. I think it has to do with the parser.

**Comment by blueloveTH** [comment]
Thanks for reporting. Please keep this issue open.

**Comment by carlkl** [comment]
What about using a PEG parser like https://github.com/aappleby/matcheroni ?

**Comment by blueloveTH** [comment]
> What about using a PEG parser like https://github.com/aappleby/matcheroni ?

pkpy can only use STL, no 3rd libraries.

**Comment by carlkl** [comment]
good to know, thank you for the clarification.  
Does this also apply for single header libraries with appropriate licenses for inclusion into pkpy?

**Comment by blueloveTH** [comment]
I'd like to let this behavior unchanged. Numbers like `0x001` are allowed. It is not necessary to add a specific logic for 10-based numbers.
