### ISSUE TITLE
[BUG] Negative exponent causes invalid literal number error

### ISSUE THREAD

**Issue by MartialPivot** [pocketpy/pocketpy#229]
### Bug description
Negative float number exponent are not supported
i.e : a = 1e-3    # causes invalid literal number error
a = 1e3 # OK

I correct the problem by adding '-' character in the list kValidChars (file lexer.cpp, line 16)

**Comment by blueloveTH** [comment]
I cannot reproduce on https://pocketpy.dev/static/web/.

![image](https://github.com/pocketpy/pocketpy/assets/28104173/1c6b65e6-7c7c-4a04-af08-82fbc2d61d9c)

**Comment by MartialPivot** [comment]
It seems the bug has already been corrected in version 1.4.3.
Thanks, 
... and great job !!!
