### ISSUE TITLE
Is it possible to use wasm like pyscript?

### ISSUE THREAD

**Issue by cemrehancavdar** [pocketpy/pocketpy#243]
Hey,

AFAIK, pocketpy is smallest python interpreter available. And it does load fast on xterm demo. 
I wonder if can use it as the way "pyscript" works. Like I want to casually wrap javascript functions to Canvas API and to some game development with it etc.

Is it possible?

**Comment by blueloveTH** [comment]
It is feasible. You can have a try.

**Comment by cemrehancavdar** [comment]
I have very little idea about it, will try to understand it how, thanks
