### ISSUE TITLE
[BUG] Evalating many small expression uses too much memory

### ISSUE THREAD

**Issue by szdytom** [pocketpy/pocketpy#263]
### Bug description

Evalating many small expression uses too much memory, is there a memory leak?

### Steps to reproduce

The following code uses more than 10GB memory, why? In ideal case, it only allocates 1 variable.

```cpp
#include "pocketpy.h"
using namespace pkpy;

char buf[1024];

int main(){
    // Create a virtual machine
    VM* vm = new VM();

	vm->exec("a = 0");
	for (int i = 0; i < 200 * 1000 * 1000; ++i)
		vm->exec("a = a + 1 # intersting loooooooooooooooooooooooooooooooong comment");

    // Dispose the virtual machine
    delete vm;
    return 0;
}
```

Compiled with code from v2.0 branch with command `g++ -std=c++17 -O1 -frtti test.cpp $(find src/ -name "*.cpp") -Iinclude -DPK_ENABLE_OS=1`

### Environment information
You need to provide these strings:
- v2.0 branch (a53d6f1621afebd6828301463d0e9d787ae51ba5)
- linux
- 64-bit

**Comment by blueloveTH** [comment]
Thanks for your report. I will investigate this soon.

May I know what kind of project you are working on with pkpy in use?

**Comment by blueloveTH** [comment]
Hi. Currently, GC triggers on function calls. There is no function calls in your code so memory won't be freed.

**Comment by blueloveTH** [comment]
I noticed a leak of `PoolExpr`.
```
PoolExpr: 8.00 KB (used) / 8.00 KB (total) - 14.25 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 total arenas
  - 0x7f5861dfd010: 0.07 MB (used) / 0.25 MB (total)

PoolExpr: 8.00 KB (used) / 8.00 KB (total) - 125014.25 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 total arenas
  - 0x7f5861dfd010: 0.07 MB (used) / 0.25 MB (total)

PoolExpr: 8.00 KB (used) / 8.00 KB (total) - 250014.25 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 total arenas
  - 0x7f5861dfd010: 0.07 MB (used) / 0.25 MB (total)

PoolExpr: 8.00 KB (used) / 8.00 KB (total) - 375014.25 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 total arenas
  - 0x7f5861dfd010: 0.07 MB (used) / 0.25 MB (total)
```

**Comment by szdytom** [comment]
> May I know what kind of project you are working on with pkpy in use?

No specific project for now, I'm just a random CS student interested in compilers and tries to learn something from pkpy. I noticed this incredible work from DBinary's QQ group, where you mentioned it.

> There is no function calls in your code so memory won't be freed. You can invoke GC manually via vm->heap.collect().

I updated the code to:

```
#include "pocketpy.h"
using namespace pkpy;

char buf[1024];

int main(){
    // Create a virtual machine
    VM* vm = new VM();

    vm->exec("a = 0");
    for (int i = 0; i < 200 * 1000 * 1000; ++i){
        vm->exec("a = a + 1 # intersting loooooooooooooooooooooooooooooooong comment");
        if (i % 200'000 == 0) {
            vm->heap.collect();
            printf("GC at i = %d\n", i);
        }
    }
    // Dispose the virtual machine
    delete vm;
    return 0;
}
```

It does not help much, it uses more than 10GB memory at i = 71000000, where I interrupted it.

I investigate the problem a little by attaching GDB to it. It looks like for some reason (maybe stacktrace?), pkpy keeps a clone of the source evaluated and never frees it, which costs up to 4.7GB memory at i = 71000000. If this is intend behavior, this issue shall be transformed into a feature request instead of bug report (because the memory is still kept by the VM object and will be free after `delete vm`).

In application scenarios such as game developing, it is extremely easy for pkpy users to write something like this:

```cpp
// Game loop
while (true) {
    // other logic
    ...
    // run script
    vm->exec("emit_event('tick')");
}
```

This will leak memory slowly and finally causing the game to crash. Maybe we should mention this pattern in the document and warn users not to wrote code like so.

**Comment by blueloveTH** [comment]
This is not a feature. Source is expected to be freed after exec.

**Comment by blueloveTH** [comment]
Well, I have pushed a fix for expr leak.
```
PoolExpr: 8.00 KB (used) / 8.00 KB (total) - 6.88 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 arenas
  - 0x7ff6bc5bb010: 0.07 MB (used) / 0.25 MB (total)

PoolExpr: 8.00 KB (used) / 8.00 KB (total) - 6.88 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 arenas
  - 0x7ff6bc5bb010: 0.07 MB (used) / 0.25 MB (total)

PoolExpr: 8.00 KB (used) / 8.00 KB (total) - 6.88 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 arenas
  - 0x7ff6bc5bb010: 0.07 MB (used) / 0.25 MB (total)

PoolExpr: 8.00 KB (used) / 8.00 KB (total) - 6.88 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 arenas
  - 0x7ff6bc5bb010: 0.07 MB (used) / 0.25 MB (total)
```

I am refactoring the module. And there are other known leaks about expr. However, I think it won't leak anymore for your case.
Could you please pull the latest and try again your code to see whether it still leaks or not?

**Comment by szdytom** [comment]
Ok. It's fixed.

**Comment by blueloveTH** [comment]
I think there are no leaks now. You can use `Pools_debug_info(buffer, size);` to get an overview of current memory pools.
```cpp

#include "pocketpy.h"
using namespace pkpy;

char membuf[2048];

int main(){
    // Create a virtual machine
    VM* vm = new VM();

	vm->exec("a = 0");
	for (int i = 0; i < 200 * 1000 * 1000; ++i){
        vm->exec("a = a + 1 # intersting loooooooooooooooooooooooooooooooong comment");
        if(i % 1000000 == 0){
            Pools_debug_info(membuf, 2048);
            printf("%s\n", membuf);
        }
    }

    // Dispose the virtual machine
    delete vm;
    return 0;
}

```
PoolExpr: 0.00 KB (used) / 8.00 KB (total) - 0.00 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 arenas
  - 0x7f96aaab8010: 0.07 MB (used) / 0.25 MB (total)

PoolExpr: 0.00 KB (used) / 8.00 KB (total) - 0.00 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 arenas
  - 0x7f96aaab8010: 0.07 MB (used) / 0.25 MB (total)

PoolExpr: 0.00 KB (used) / 8.00 KB (total) - 0.00 KB (exceeded)
PoolFrame: 0.00 KB (used) / 10.00 KB (total) - 0.00 KB (exceeded)
PoolObject: 0 empty arenas, 1 arenas
  - 0x7f96aaab8010: 0.07 MB (used) / 0.25 MB (total)
```
