### ISSUE TITLE
[Feature] Enable GCC-7 Support

### ISSUE THREAD

**Issue by FeibHwang** [pocketpy/pocketpy#272]
**It would be great if pocketpy can support GCC-7 Build**
I know GCC-7 doesn't have FULL C++17 support, but looks pocketpy used most of the GCC-7 compatible C++17 features
Here I just listed some issues I hit and my local fix

**Test command**
`g++-7 --std=c++17 main.cpp -o main -lstdc++fs`
Test with g++ 7.3.0

**1. Inline Namespace Issue**

GCC-7 and GCC-8 above handle inline namespaces differently, this will cause GCC-7 build break with error like
```
 error: reference to 'std' is ambiguous
 #define PK_FATAL_ERROR() throw std::runtime_error( "L" + std::to_string(__LINE__) + " FATAL_ERROR()!");
                                 ^
 pocketpy.h:279:31: note: in expansion of macro 'PK_FATAL_ERROR'
  #define PK_ASSERT(x) if(!(x)) PK_FATAL_ERROR();
                                ^~~~~~~~~~~~~~
 pocketpy.h:16511:5: note: in expansion of macro 'PK_ASSERT'
      PK_ASSERT(!vm->_c.s_view.empty());
      ^~~~~~~~~
<built-in>: note: candidates are: namespace std { }
```

The issue is in header `include/pocketpy/common.h`:

```
namespace pkpy{
namespace std = ::std;
...
#define PK_FATAL_ERROR() throw std::runtime_error( "L" + std::to_string(__LINE__) + " FATAL_ERROR()!");
}
```

GCC-8+ is thinking `std::runtime_error`, while GCC-7 thinks `pkpy::std::runtime_error`
My current solution is just removing the namespace "namespace std = ::std;", but it would be great to add macro protection, this namespace alias can only enable in GCC-8 and above
```
namespace pkpy{
#if defined(__GNUC__) && (__GNUC__ >= 8)
namespace std = ::std;
#endif
...
#define PK_FATAL_ERROR() throw std::runtime_error( "L" + std::to_string(__LINE__) + " FATAL_ERROR()!");
}
```

**2. Experimental File System**
This only happened to `main.cpp` which include filesystem directly, for GCC-7 the filesystem is still in experiment folder, here is a macro I used to handle real filesystem and experimental file system:
```
#if __has_include(<filesystem>)
  #include <filesystem>
  namespace fs = std::filesystem;
#elif __has_include(<experimental/filesystem>)
  #include <experimental/filesystem>
  namespace fs = std::experimental::filesystem;
#else
  #error Unknown compiler filesystem handler 
#endif

//std::filesystem::path m_path
fs::path m_path;
```

Thanks,
Nice Project !

**Comment by blueloveTH** [comment]
We are working on the move of reimpl everything in C11. See v2.0-c11 branch.

I think these problems will be solved on C11 release.

**Comment by FeibHwang** [comment]
Confirmed branch v2.0-c11 branch can resolve the issues, will keep tracking on the new branch development
Thank you
