### ISSUE TITLE
HelloGitHub Badge

### ISSUE THREAD

**Issue by 521xueweihan** [pocketpy/pocketpy#273]
🎉 Congratulations! Your [project](https://hellogithub.com/repository/dd9c509d72a64caca03d99d5b1991a33) has been featured and recommended by the HelloGitHub community. We invite you to join the HelloGitHub Badge Program. Joining will grant you the following privileges:

- **Community Recognition**: The badge indicates that your project has successfully passed the HelloGitHub community's stringent selection and recommendation process.
- **Increased Exposure**: Displaying the badge will draw more traffic to your project, attracting additional users and contributors.
- **Enhanced Interaction**: Users can quickly understand your project through the badge and engage with it (like, comment, bookmark).
- **Feedback Collection**: Gather genuine feedback from a broad user base, aiding in the continuous improvement of your project.
- **Special Identification**: Once verified, your comments will feature a distinctive mark and be prioritized for pinning.

📌 [Click here](https://hellogithub.com/repository/dd9c509d72a64caca03d99d5b1991a33/embed) to wear the badge and join the HelloGitHub Badge Program, allowing your open-source project to shine even brighter.

<img width="740" alt="image" src="https://github.com/pocketpy/pocketpy/assets/8255800/a20372d1-55c5-4790-9b6c-3026685f12d4">

---

**HelloGitHub** is a community focused on discovering, sharing, and promoting open-source projects. Since its inception in 2016, it has grown from a monthly newsletter into a dynamic community with over **10,000** users. Our footprint extends across multiple content platforms, earning the trust and support of **500,000** fans worldwide.

**Comment by blueloveTH** [comment]
Thanks for your information. We are busy at v2 dev recently.
I'd like to respond for you after the v2 release. I think that is the right time to enlarge our community.

**Comment by 521xueweihan** [comment]
> Thanks for your information. We are busy at v2 dev recently. I'd like to respond you after the v2 release. I think that is the right time to enlarge our community.

OK.

**Comment by 521xueweihan** [comment]
<img width="721" alt="image" src="https://github.com/user-attachments/assets/27e9536f-703e-46c7-942c-0be993d8336e">

@blueloveTH Hello, I have modified the description and tags of the project, but the main language is mapped to the main language on GitHub and cannot be modified. Please understand.

**Comment by blueloveTH** [comment]
Thank you.
