### ISSUE TITLE
[Question] Compile to WASI with clang

### ISSUE THREAD

**Issue by orsinium** [pocketpy/pocketpy#275]
Code:

```cpp
#include "../vendor/pocketpy.h"

using namespace pkpy;

int main()
{
    VM *vm = new VM();
    vm->exec("a = [1, 2, 3]");
    return 0;
}
```

Command:

```bash
./wasi-sdk-20.0/bin/clang++ --sysroot="$PWD/wasi-sdk-20.0/share/wasi-sysroot"-o build/cart.wasm   build/main.o -mexec-model=reactor -Wl,--stack-first -Wl,--strip-all,--gc-sections,--lto-O3 -Oz
```

Output:

```
wasm-ld: error: build/main.o: undefined symbol: __cxa_allocate_exception
wasm-ld: error: build/main.o: undefined symbol: __cxa_throw
wasm-ld: error: build/main.o: undefined symbol: __cxa_allocate_exception
wasm-ld: error: build/main.o: undefined symbol: __cxa_throw
wasm-ld: error: build/main.o: undefined symbol: __cxa_allocate_exception
wasm-ld: error: build/main.o: undefined symbol: __cxa_throw
wasm-ld: error: build/main.o: undefined symbol: __cxa_allocate_exception
wasm-ld: error: build/main.o: undefined symbol: __cxa_throw
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do I do something wrong? I tried adding `-fwasm-exceptions`, doesn't help.

**Comment by orsinium** [comment]
I wasn't sure if to mark it as Feature or as Bug. At the end, I decided to call it a Question. After all, it's probably me who's doing something wrong. I managed to compile pocketpy to wasm using emscripten using `build_web.sh` but it requires a custom emscripten JS bridge to work, which makes it suitable only for web. And wasm is more than just web.

**Comment by shailist** [comment]
If you read [the last part of the README of wasi-sdk](https://github.com/WebAssembly/wasi-sdk) you'll see that it does not support C++ exceptions, and as pocketpy requires C++ exceptions to be enabled, you can't compile it with wasi-sdk.

**Comment by blueloveTH** [comment]
I am not familiar with wasi. And we are reimpl-ing the core interpreter in C11 which does not require exceptions.

**Comment by orsinium** [comment]
> I am not familiar with wasi. 

WASI is a system interface for WASM. When pocketpy compiled to wasm tries, let's say, open a file, wasi describes what host functions it can call to do that. And wasi-libc is a toolchain that compile C/C++ code replacing libc with [wasi-libc](https://github.com/WebAssembly/wasi-libc) that uses this WASI interface.

In other words, WASI is what you have to use if you compile to WASM but not for web. 

> And we are reimpl-ing the core interpreter in C11 which does not require exceptions.

Great! Let's hope then that #265 will solve this issue.

**Comment by orsinium** [comment]
> you'll see that it does not support C++ exceptions, and as pocketpy requires C++ exceptions to be enabled, you can't compile it with wasi-sdk.

Do you know if there is a way to tell wasi-sdk to turn exceptions into `unreachable`? 🤔 If pocketpy doesn't use exceptions for control flow, that should do the trick.

**Comment by blueloveTH** [comment]
Without exceptions, pocketpy still works but all python's `try..except` won't work anymore.

**Comment by shailist** [comment]
> > you'll see that it does not support C++ exceptions, and as pocketpy requires C++ exceptions to be enabled, you can't compile it with wasi-sdk.
> 
> Do you know if there is a way to tell wasi-sdk to turn exceptions into `unreachable`? 🤔 If pocketpy doesn't use exceptions for control flow, that should do the trick.

you can always just define and implement the missing functions yourself and make them do whatever you want

**Comment by orsinium** [comment]
So, I can just define `__cxa_allocate_exception`? 🤔 Sorry, I'm new to C/C++. Like, VERY new. I'll give it a try 👍🏿

**Comment by blueloveTH** [comment]
@orsinium Hi. pocketpy v2 is in alpha stage now! It is pure C11. No need to consider exception or rtti anymore.
You can try v2 in the `main` branch.

**Comment by orsinium** [comment]
Amazing work! @kopchik is now handling the work on bringing PocketPy to Firefly. I know he tried using v2 but had some issues. I believe string concatenation doesn't work? I asked him to bring his feedback here :)

**Comment by kopchik** [comment]
I confirm that string concatenation is now working with the latest update. I proceed with more thorough testing.

```
>>> 'x'+'y'
'xy'
```
