### ISSUE TITLE
[Feature] Please allow non-static stdout/stderr options

### ISSUE THREAD

**Issue by WalkerWhite** [pocketpy/pocketpy#292]
I really like this library, but I have a use case with multiple compartmentalized VMs. As such, I need to keep the stdout/stderr separate between these VMs. Fortunately, it is possible to assign custom stdout/stderr functions to each VM.  Unfortunately, it is only possible to assign static functions to these values.  That means the number of VMs cannot scale dynamically.  I essentially have to create a pool of statically allocated VMs from the start, which is wasteful.

The problem is that the VM uses C-style function pointers and not std::function.  That means it is impossible to assign a capture lambda to stdout/stderr.  Using std::function here would be so much nicer.

**Comment by blueloveTH** [comment]
`VM::stdout_write` and `VM::stderr_write` are virtual, you can override it.

**Comment by WalkerWhite** [comment]
That's embarassing.  To be fair, when I see a function pointer variable I normally don't think about subclassing.  But this solves this issue.  Thanks.
