### ISSUE TITLE
[BUG] pocketpy.h: No such file or directory when embedding pkpy

### ISSUE THREAD

**Issue by kopchik** [pocketpy/pocketpy#297]
Hi!

I'm trying to embed pocketpy using cmake following this tutorial: https://pocketpy.dev/quick-start/#use-cmake . I've got an issue that `pocketpy.h` is not found. Here is the test project that shows the problem: https://github.com/kopchik/pkpy-example

This can be fixed if I add this line to my cmake configuration, but I'm not sure if this is an idiomatic solution:
```cmake
include_directories(${CMAKE_CURRENT_LIST_DIR}/pocketpy/include)
```

Could you please suggest what would be a proper fix for include search path?

**Comment by blueloveTH** [comment]
Yes. You should do this in your own cmake list file.
