### ISSUE TITLE
[Feature] status of bind11?

### ISSUE THREAD

**Issue by kopchik** [pocketpy/pocketpy#298]
Hi again)

I have some code that uses pkpy 1.46 and pybind11. How to port it to pkpy 2.0? I cannot find, say, `PYBIND11_EMBEDDED_MODULE`. Also `pocketpy/include/pybind11` hasn't been updated in a while. So, I guess, it's not supported yet?

**Comment by blueloveTH** [comment]
pybind11 will be supported in v2 very soon! Please allow me to invite @16bit-ykiko to say some thing about this.

**Comment by 16bit-ykiko** [comment]
I expect to complete the migration this week, so just wait for a moment 🙂.
